/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetV1UsersMe200ResponseData } from './GetV1UsersMe200ResponseData';
import {
    GetV1UsersMe200ResponseDataFromJSON,
    GetV1UsersMe200ResponseDataFromJSONTyped,
    GetV1UsersMe200ResponseDataToJSON,
} from './GetV1UsersMe200ResponseData';

/**
 * 
 * @export
 * @interface GetV1UsersMe200Response
 */
export interface GetV1UsersMe200Response {
    /**
     * 
     * @type {string}
     * @memberof GetV1UsersMe200Response
     */
    status: string;
    /**
     * 
     * @type {GetV1UsersMe200ResponseData}
     * @memberof GetV1UsersMe200Response
     */
    data: GetV1UsersMe200ResponseData;
}

/**
 * Check if a given object implements the GetV1UsersMe200Response interface.
 */
export function instanceOfGetV1UsersMe200Response(value: object): value is GetV1UsersMe200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetV1UsersMe200ResponseFromJSON(json: any): GetV1UsersMe200Response {
    return GetV1UsersMe200ResponseFromJSONTyped(json, false);
}

export function GetV1UsersMe200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1UsersMe200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': GetV1UsersMe200ResponseDataFromJSON(json['data']),
    };
}

export function GetV1UsersMe200ResponseToJSON(value?: GetV1UsersMe200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': GetV1UsersMe200ResponseDataToJSON(value['data']),
    };
}

