/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetV1UsersId200ResponseData
 */
export interface GetV1UsersId200ResponseData {
    /**
     * The name of the user.
     * @type {string}
     * @memberof GetV1UsersId200ResponseData
     */
    name: string;
    /**
     * The email of the user.
     * @type {string}
     * @memberof GetV1UsersId200ResponseData
     */
    email: string;
}

/**
 * Check if a given object implements the GetV1UsersId200ResponseData interface.
 */
export function instanceOfGetV1UsersId200ResponseData(value: object): value is GetV1UsersId200ResponseData {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function GetV1UsersId200ResponseDataFromJSON(json: any): GetV1UsersId200ResponseData {
    return GetV1UsersId200ResponseDataFromJSONTyped(json, false);
}

export function GetV1UsersId200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1UsersId200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
    };
}

export function GetV1UsersId200ResponseDataToJSON(value?: GetV1UsersId200ResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

