/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetV1UsersMe400ResponseError
 */
export interface GetV1UsersMe400ResponseError {
    /**
     * 
     * @type {string}
     * @memberof GetV1UsersMe400ResponseError
     */
    message: string;
}

/**
 * Check if a given object implements the GetV1UsersMe400ResponseError interface.
 */
export function instanceOfGetV1UsersMe400ResponseError(value: object): value is GetV1UsersMe400ResponseError {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetV1UsersMe400ResponseErrorFromJSON(json: any): GetV1UsersMe400ResponseError {
    return GetV1UsersMe400ResponseErrorFromJSONTyped(json, false);
}

export function GetV1UsersMe400ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1UsersMe400ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function GetV1UsersMe400ResponseErrorToJSON(value?: GetV1UsersMe400ResponseError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

