/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetV1UsersId200ResponseData } from './GetV1UsersId200ResponseData';
import {
    GetV1UsersId200ResponseDataFromJSON,
    GetV1UsersId200ResponseDataFromJSONTyped,
    GetV1UsersId200ResponseDataToJSON,
} from './GetV1UsersId200ResponseData';

/**
 * 
 * @export
 * @interface GetV1UsersId200Response
 */
export interface GetV1UsersId200Response {
    /**
     * 
     * @type {string}
     * @memberof GetV1UsersId200Response
     */
    status: string;
    /**
     * 
     * @type {GetV1UsersId200ResponseData}
     * @memberof GetV1UsersId200Response
     */
    data: GetV1UsersId200ResponseData;
}

/**
 * Check if a given object implements the GetV1UsersId200Response interface.
 */
export function instanceOfGetV1UsersId200Response(value: object): value is GetV1UsersId200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetV1UsersId200ResponseFromJSON(json: any): GetV1UsersId200Response {
    return GetV1UsersId200ResponseFromJSONTyped(json, false);
}

export function GetV1UsersId200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1UsersId200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': GetV1UsersId200ResponseDataFromJSON(json['data']),
    };
}

export function GetV1UsersId200ResponseToJSON(value?: GetV1UsersId200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': GetV1UsersId200ResponseDataToJSON(value['data']),
    };
}

