/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetV1UsersMe400ResponseError } from './GetV1UsersMe400ResponseError';
import {
    GetV1UsersMe400ResponseErrorFromJSON,
    GetV1UsersMe400ResponseErrorFromJSONTyped,
    GetV1UsersMe400ResponseErrorToJSON,
} from './GetV1UsersMe400ResponseError';

/**
 * 
 * @export
 * @interface PostV1Echo200Response
 */
export interface PostV1Echo200Response {
    /**
     * 
     * @type {string}
     * @memberof PostV1Echo200Response
     */
    status: string;
    /**
     * 
     * @type {GetV1UsersMe400ResponseError}
     * @memberof PostV1Echo200Response
     */
    data: GetV1UsersMe400ResponseError;
}

/**
 * Check if a given object implements the PostV1Echo200Response interface.
 */
export function instanceOfPostV1Echo200Response(value: object): value is PostV1Echo200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PostV1Echo200ResponseFromJSON(json: any): PostV1Echo200Response {
    return PostV1Echo200ResponseFromJSONTyped(json, false);
}

export function PostV1Echo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV1Echo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': GetV1UsersMe400ResponseErrorFromJSON(json['data']),
    };
}

export function PostV1Echo200ResponseToJSON(value?: PostV1Echo200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': GetV1UsersMe400ResponseErrorToJSON(value['data']),
    };
}

