/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetV1UsersMe400Response,
  GetV1UsersMe400ResponseError,
  PostV1Echo200Response,
} from '../models/index';
import {
    GetV1UsersMe400ResponseFromJSON,
    GetV1UsersMe400ResponseToJSON,
    GetV1UsersMe400ResponseErrorFromJSON,
    GetV1UsersMe400ResponseErrorToJSON,
    PostV1Echo200ResponseFromJSON,
    PostV1Echo200ResponseToJSON,
} from '../models/index';

export interface PostV1EchoRequest {
    getV1UsersMe400ResponseError?: GetV1UsersMe400ResponseError;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @param {GetV1UsersMe400ResponseError} [getV1UsersMe400ResponseError] POST /v1/echo Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postV1EchoRaw(requestParameters: PostV1EchoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostV1Echo200Response>>;

    /**
     */
    postV1Echo(requestParameters: PostV1EchoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostV1Echo200Response>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     */
    async postV1EchoRaw(requestParameters: PostV1EchoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostV1Echo200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/echo`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetV1UsersMe400ResponseErrorToJSON(requestParameters['getV1UsersMe400ResponseError']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostV1Echo200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async postV1Echo(requestParameters: PostV1EchoRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostV1Echo200Response> {
        const response = await this.postV1EchoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
