/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetV1UsersMe200Response,
  GetV1UsersMe400Response,
} from '../models/index';
import {
    GetV1UsersMe200ResponseFromJSON,
    GetV1UsersMe200ResponseToJSON,
    GetV1UsersMe400ResponseFromJSON,
    GetV1UsersMe400ResponseToJSON,
} from '../models/index';

export interface GetV1UsersIdRequest {
    id: string;
}

/**
 * UsersApi - interface
 * 
 * @export
 * @interface UsersApiInterface
 */
export interface UsersApiInterface {
    /**
     * Retrieves the user by id.
     * @summary Retrieves the user by id.
     * @param {string} id GET /v1/users/:id Parameter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getV1UsersIdRaw(requestParameters: GetV1UsersIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetV1UsersMe200Response>>;

    /**
     * Retrieves the user by id.
     * Retrieves the user by id.
     */
    getV1UsersId(requestParameters: GetV1UsersIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetV1UsersMe200Response>;

    /**
     * Retrieves the current user profile.
     * @summary Retrieves the current user profile.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getV1UsersMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetV1UsersMe200Response>>;

    /**
     * Retrieves the current user profile.
     * Retrieves the current user profile.
     */
    getV1UsersMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetV1UsersMe200Response>;

}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI implements UsersApiInterface {

    /**
     * Retrieves the user by id.
     * Retrieves the user by id.
     */
    async getV1UsersIdRaw(requestParameters: GetV1UsersIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetV1UsersMe200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getV1UsersId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetV1UsersMe200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the user by id.
     * Retrieves the user by id.
     */
    async getV1UsersId(requestParameters: GetV1UsersIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetV1UsersMe200Response> {
        const response = await this.getV1UsersIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the current user profile.
     * Retrieves the current user profile.
     */
    async getV1UsersMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetV1UsersMe200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/users/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetV1UsersMe200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the current user profile.
     * Retrieves the current user profile.
     */
    async getV1UsersMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetV1UsersMe200Response> {
        const response = await this.getV1UsersMeRaw(initOverrides);
        return await response.value();
    }

}
