services:
  website:
    profiles:
      - build_docker_images
    image: website:${VERSION}
    build:
      context: ../.
      dockerfile: ./deployment_scripts/Dockerfile.website

  backend:
    profiles:
      - build_docker_images
    image: backend:${VERSION}
    build:
      context: ../.
      dockerfile: ./deployment_scripts/Dockerfile.backend

  npm_builder:
    profiles:
      - build_dist_folders
    restart: 'no'
    image: node:20.13.0-alpine3.18
    working_dir: /src
    command:
      [
        'sh',
        '-cx',
        "corepack enable && corepack pnpm i && corepack pnpm build && chmod -R 777 .pnpm-store && find . -name 'node_modules' -type d -prune -exec chmod -R 777 '{}' +"
      ]
    volumes:
      - ../:/src:rw
